### ISSUE TITLE
Undefined local variable `occurrence_counter`

### ISSUE THREAD

**Issue by holman** [fractaledmind/solid_errors#16]
Upgrading to the email notifications and getting this currently:

```
ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [65ec43aa-b13e-4a96-aa7b-67770a3e6d79]
Error performing ActionMailer::MailDeliveryJob (Job ID: 65ec43aa-b13e-4a96-aa7b-67770a3e6d79)
from Async(default) in 97.84ms: ActionView::Template::Error (undefined local variable or method `occurrence_counter' for #<ActionView::Base:0x00000000054dd0>):
```

This also has the unfortunate side effect of continually looping into error after error as I think `solid_errors` is catching the error from this and trying to report the error, which then raises an error...

**Comment by fractaledmind** [comment]
Fixed by #28
