### ISSUE TITLE
Expiration or Ability to Delete Errors/Occurrences

### ISSUE THREAD

**Issue by acoffman** [fractaledmind/solid_errors#4]
Hi, I love the idea for this! Already been playing around with it some today.

One thing that might be useful is the ability to remove Errors (and their occurrences) either after a certain expiration time or manually via the UI. That way the database size doesn't grow unbounded.

I know one of the primary goals is to keep things simple, but is that functionality you'd be interesting in including? I could probably work on a PR if so.

**Comment by fractaledmind** [comment]
Yeah, my thinking currently is to start by adding another page for showing resolved errors and on that page allow for manual deletion. I don't want to add automatic deletion yet, because that will require some kind of scheduled work, which immediately adds meaningful complexity.

**Comment by fractaledmind** [comment]
Feel free to open a PR with the resolved errors index view and a destroy action
