### ISSUE TITLE
Usage with rails-api

### ISSUE THREAD

**Issue by riteshnoronha** [fractaledmind/solid_errors#6]
Not an issue as such, but for about documentation. 

To get this working with rails api i added the following to config/environments/development.rb 

```
  config.middleware.use ActionDispatch::Cookies
  config.middleware.use ActionDispatch::Session::CookieStore
  config.middleware.use ActionDispatch::Flash
```

**Comment by fractaledmind** [comment]
Can you elaborate on what problems you were hitting in Solid Errors that were then fixed by telling Rails to use these middlewares?

**Comment by riteshnoronha** [comment]
@fractaledmind the exceptions were being logged to the DB, but when i tried loading the page, it was crashing saying flash was'nt present  My app is a rails api based app, which does not have any of the view layer stuff, i however have ui enabled for graphiql using https://github.com/rmosolgo/graphiql-rails?tab=readme-ov-file#note-on-api-mode, in addition to this i had to add the above middleware. For solid error however, it was crashing on missing flash. So thats the only middleware i had to add, in addition to the ones i already had. 

I have not tried this is a vanilla rails api based app.

**Comment by riteshnoronha** [comment]
In production, we do not allow any UI access. We use solid error only for our staging and dev environments. For production we use sentry and newrelic.
